### ISSUE TITLE
Some errors on the for-influxdb-v2.json

### ISSUE THREAD

**Issue by fsaqv** [krakendio/telemetry-dashboards#1]
#### Environment info:
grafana/krakend/for-influxdb-v2.json: latest
Grafana: v9.1.6
System info: docker / k8s

#### Describe what are you trying to do:
Hi guys, I'm trying to send data from multiple krakend kubernetes pods, running at same namespace to one influxb2 database instanse.
But dashboard host selector is broken. If "all" or multiple hosts selected, we have error in reqest:
> from(bucket: "krakend")
>    |> range(start: 2022-10-03T23:05:03.495Z, stop: 2022-10-04T11:05:03.496Z)
    |> filter(fn: (r) => r._measurement == "responses" and r._field == "count" and r.host =~ /{gateway-public-5d6c4fbdf-gcx2h,gateway-public-9f585b4d7-mlnvn,gateway-public-7c568f66b8-m9z7j}/)
>    |> group(columns: ["name","status"], mode: "by")
>    |> aggregateWindow(every: 20m, fn: sum)
>    |> yield()

>invalid: compilation failed: error @3:94-3:197: regex parse error: 
>{gateway-public-5d6c4fbdf-gcx2h,gateway-public-9f585b4d7-mlnvn,gateway-public-mr-15-7c568f66b8-m9z7j} error:
>repetition operator missing expression

Any suggestions?

**Comment by alombarte** [comment]
I tried a few times, but I cannot reproduce it. Please reopen if you are still facing this issue, although the new Grafana dashboard we support is based on Prometheus.
